spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/bowling_reservation_system
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  session:
    store-type: jdbc

server:
  error:
    include-message: always

application:
  managerPassword: poet-homecoming-group-try
